name: live_kirtan
description: "Sarvan Karo Live Kirtan Sri Harimandir Sahib."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
